In [13]:
import pandas as pd
import numpy as np

In [106]:
data = pd.read_csv('heart_disease.csv')
data['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [17]:
data.drop(columns=['education'])
# data['Gender'].unique()

Gender  age  currentSmoker  cigsPerDay  BPMeds prevalentStroke  \
0          1   39              0         0.0     0.0              no   
1          0   46              0         0.0     0.0              no   
2          1   48              1        20.0     0.0              no   
3          0   61              1        30.0     0.0              no   
4          0   46              1        23.0     0.0              no   
...      ...  ...            ...         ...     ...             ...   
4233       1   50              1         1.0     0.0              no   
4234       1   51              1        43.0     0.0              no   
4235       0   48              1        20.0     NaN              no   
4236       0   44              1        15.0     0.0              no   
4237       0   52              0         0.0     0.0              no   

      prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  \
0                0         0    195.0  106.0   70.0  26.97       80.0   
1                0         0    250.0  121.0   81.0  28.73       95.0   
2                0         0    245.0  127.5   80.0  25.34       75.0   
3                1         0    225.0  150.0   95.0  28.58       65.0   
4                0         0    285.0  130.0   84.0  23.10       85.0   
...            ...       ...      ...    ...    ...    ...        ...   
4233             1         0    313.0  179.0   92.0  25.97       66.0   
4234             0         0    207.0  126.5   80.0  19.71       65.0   
4235             0         0    248.0  131.0   72.0  22.00       84.0   
4236             0         0    210.0  126.5   87.0  19.16       86.0   
4237             0         0    269.0  133.5   83.0  21.47       80.0   

      glucose Heart_ stroke  
0        77.0            No  
1        76.0            No  
2        70.0            No  
3       103.0           yes  
4        85.0            No  
...       ...           ...  
4233     86.0           yes  
4234     68.0            No  
4235     86.0            No  
4236      NaN            No  
4237    107.0            No  

[4238 rows x 15 columns]

In [35]:
data['Gender'] = data['Gender'].replace(['Male','Female'],[1,0])
# data.drop(columns=['education'],inplace=True)
data['prevalentStroke'] = data['prevalentStroke'].replace(['no','yes'],[1,0])

In [36]:
data['prevalentStroke'].unique()

array([1, 0], dtype=int64)

In [37]:
data

Gender  age  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0          1   39              0         0.0     0.0                1   
1          0   46              0         0.0     0.0                1   
2          1   48              1        20.0     0.0                1   
3          0   61              1        30.0     0.0                1   
4          0   46              1        23.0     0.0                1   
...      ...  ...            ...         ...     ...              ...   
4233       1   50              1         1.0     0.0                1   
4234       1   51              1        43.0     0.0                1   
4235       0   48              1        20.0     NaN                1   
4236       0   44              1        15.0     0.0                1   
4237       0   52              0         0.0     0.0                1   

      prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  \
0                0         0    195.0  106.0   70.0  26.97       80.0   
1                0         0    250.0  121.0   81.0  28.73       95.0   
2                0         0    245.0  127.5   80.0  25.34       75.0   
3                1         0    225.0  150.0   95.0  28.58       65.0   
4                0         0    285.0  130.0   84.0  23.10       85.0   
...            ...       ...      ...    ...    ...    ...        ...   
4233             1         0    313.0  179.0   92.0  25.97       66.0   
4234             0         0    207.0  126.5   80.0  19.71       65.0   
4235             0         0    248.0  131.0   72.0  22.00       84.0   
4236             0         0    210.0  126.5   87.0  19.16       86.0   
4237             0         0    269.0  133.5   83.0  21.47       80.0   

      glucose Heart_ stroke  
0        77.0            No  
1        76.0            No  
2        70.0            No  
3       103.0           yes  
4        85.0            No  
...       ...           ...  
4233     86.0           yes  
4234     68.0            No  
4235     86.0            No  
4236      NaN            No  
4237    107.0            No  

[4238 rows x 15 columns]

In [40]:
data.dropna(inplace=True)
data['Heart_ stroke'].unique()

array(['No', 'yes'], dtype=object)

In [41]:
data['Heart_ stroke'] = data['Heart_ stroke'].replace(['No' ,'yes'],[0,1])

In [42]:
data

Gender  age  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0          1   39              0         0.0     0.0                1   
1          0   46              0         0.0     0.0                1   
2          1   48              1        20.0     0.0                1   
3          0   61              1        30.0     0.0                1   
4          0   46              1        23.0     0.0                1   
...      ...  ...            ...         ...     ...              ...   
4231       1   58              0         0.0     0.0                1   
4232       1   68              0         0.0     0.0                1   
4233       1   50              1         1.0     0.0                1   
4234       1   51              1        43.0     0.0                1   
4237       0   52              0         0.0     0.0                1   

      prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  \
0                0         0    195.0  106.0   70.0  26.97       80.0   
1                0         0    250.0  121.0   81.0  28.73       95.0   
2                0         0    245.0  127.5   80.0  25.34       75.0   
3                1         0    225.0  150.0   95.0  28.58       65.0   
4                0         0    285.0  130.0   84.0  23.10       85.0   
...            ...       ...      ...    ...    ...    ...        ...   
4231             1         0    187.0  141.0   81.0  24.96       80.0   
4232             1         0    176.0  168.0   97.0  23.14       60.0   
4233             1         0    313.0  179.0   92.0  25.97       66.0   
4234             0         0    207.0  126.5   80.0  19.71       65.0   
4237             0         0    269.0  133.5   83.0  21.47       80.0   

      glucose  Heart_ stroke  
0        77.0              0  
1        76.0              0  
2        70.0              0  
3       103.0              1  
4        85.0              0  
...       ...            ...  
4231     81.0              0  
4232     79.0              1  
4233     86.0              1  
4234     68.0              0  
4237    107.0              0  

[3749 rows x 15 columns]

In [ ]:
#input , output create

In [44]:
input_dataset = data.drop(columns=['Heart_ stroke'])
output_dataset = data['Heart_ stroke']
input_dataset

Gender  age  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0          1   39              0         0.0     0.0                1   
1          0   46              0         0.0     0.0                1   
2          1   48              1        20.0     0.0                1   
3          0   61              1        30.0     0.0                1   
4          0   46              1        23.0     0.0                1   
...      ...  ...            ...         ...     ...              ...   
4231       1   58              0         0.0     0.0                1   
4232       1   68              0         0.0     0.0                1   
4233       1   50              1         1.0     0.0                1   
4234       1   51              1        43.0     0.0                1   
4237       0   52              0         0.0     0.0                1   

      prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  
0                0         0    195.0  106.0   70.0  26.97       80.0     77.0  
1                0         0    250.0  121.0   81.0  28.73       95.0     76.0  
2                0         0    245.0  127.5   80.0  25.34       75.0     70.0  
3                1         0    225.0  150.0   95.0  28.58       65.0    103.0  
4                0         0    285.0  130.0   84.0  23.10       85.0     85.0  
...            ...       ...      ...    ...    ...    ...        ...      ...  
4231             1         0    187.0  141.0   81.0  24.96       80.0     81.0  
4232             1         0    176.0  168.0   97.0  23.14       60.0     79.0  
4233             1         0    313.0  179.0   92.0  25.97       66.0     86.0  
4234             0         0    207.0  126.5   80.0  19.71       65.0     68.0  
4237             0         0    269.0  133.5   83.0  21.47       80.0    107.0  

[3749 rows x 14 columns]

In [50]:
# print(len(input_dataset))
# print(len(output_dataset))

In [51]:
output_dataset.value_counts()
#impalanced data not equal

Heart_ stroke
0    3177
1     572
Name: count, dtype: int64

In [56]:
pip install imblearn

In [70]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=2)
input_dataset,output_dataset=sm.fit_resample(input_dataset,output_dataset.ravel())
np.unique(data_output , return_counts=True)
# data is equal

(array([0, 1], dtype=int64), array([3177, 3177], dtype=int64))

In [71]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [78]:
x_train,x_test,y_train,y_test = train_test_split(input_dataset,output_dataset, test_size=0.2)
model = LogisticRegression()
model.fit(x_train,y_train)

C:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [81]:
model.score(x_test,y_test)

0.6514555468135327

In [85]:
model.score(x_test,y_test)

0.6514555468135327

In [86]:
input = np.array([[0,61,1,30,0,0,1,0,225,150,95,28.58,65,103]])
model.predict(input)

C:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [102]:
# pip install pickle5
# visual start

In [104]:
import pickle as pk
pk.dump(model,open('Heart_disease_model.pk1','wb'))

In [105]:
pip install streamlit

Note: you may need to restart the kernel to use updated packages.
